#!/bin/bash
# Start Elk JUCE example

sushi -r --multicore-processing=2 -c ./sushi-configs/obxd_step.json &

sensei -f /usr/share/sensei/blackboard.json &

(cd ./apps; ./main_app_minimal &)

sleep 3

aconnect 16 128


