#!/bin/bash
# Start Elk JUCE example

./stop
sleep 1
sudo systemctl start sensei
sleep 1
sushi -r --multicore-processing=2 -c ../../multi-fx/elk_multi_fx_pi.json &
sleep 1
(cd ./apps; ./main_app_general &)
sleep 3
aconnect -x
aconnect 16 128
