#!/bin/bash
# Start Elk JUCE example

OBXD_PLUGIN_PATH=/udata/elk-examples/plugins/Obxd.so

if ! test -f "$OBXD_PLUGIN_PATH"; then
    echo "Error! Plugin OB-Xd is missing. Please download the plugins for the examples and place them\
 in /udata/elk-examples/plugins. Documentation and a link for the plugins can be found at: \
https://elk-audio.github.io/elk-docs/html/documents/elk_examples_overview.html#complete-blackboard-examples"
    exit 0
fi

./stop
sleep 1
sudo systemctl start sensei
sleep 1
sushi -r --multicore-processing=2 -c ./sushi-configs/obxd_step.json &
sleep 1
(cd ./apps; ./main_app_general &)
sleep 3
aconnect -x

MIDI_KEYBOARD="$(aconnect -l)"
if ! echo "$MIDI_KEYBOARD" | grep -q "16"; then
    echo "No MIDI keyboard found connected to the USB ports. Connect one to play synth, or use Blackboard buttons."
fi

aconnect 16 128
