#!/bin/bash
# Start Elk Sequencer example

sushi -r  --multicore-processing=2 -c ./sushi-configs/sushi_config.json &

sensei -f /usr/share/sensei/blackboard.json &

(cd ./main; ./main_app &)

sleep 3

aconnect 16 128


