#!/bin/bash
# Start Elk Sequencer example

sushi -r  --multicore-processing=2 -c ./sushi-configs/sushi_config.json &

sudo systemctl start sensei

(cd ./main; ./main_app_without_elk_ui &)

sleep 3

aconnect 16 128


