#!/bin/bash
# Start Elk Sequencer example

sushi -r  --multicore-processing=2 -c ../configs/sushi/sushi_config.json &

sensei -f ../configs/sensei/sensei_config.json &

./main_app &

sleep 3

aconnect 16 128


