#!/bin/bash
# Start Elk JUCE example

JUCE_PLUGIN_PATH=/udata/ElkJuceExample.vst3/Contents/aarch64-linux/ElkJuceExample.so

if ! test -f "$JUCE_PLUGIN_PATH"; then
    echo "Error! Elk Juce example plugin is missing. Please download the plugins for the examples and place them\
 in /udata/elk-examples/plugins. Documentation and a link for the plugins can be found at: \
https://elk-audio.github.io/elk-docs/html/documents/elk_examples_overview.html#complete-blackboard-examples"
    exit 0
fi

MIDI_KEYBOARD="$(aconnect -l)"
if ! echo "$MIDI_KEYBOARD" | grep -q "16"; then
    echo "Error! Midi Keyboard not connected. Please connect one, this example depends on it."
    exit 0
fi

./stop
sleep 1
sudo systemctl start sensei
sleep 1
sushi -r  --multicore-processing=2 -c ./sushi-configs/sushi_config.json &
sleep 1
(cd ./main; ./main_app &)
sleep 3
aconnect -x
aconnect 16 128
