#!/bin/bash
# Start Elk JUCE example

sushi -r --multicore-processing=2 -c ./sushi-configs/sushi_config.json &

sensei -f ../common-files/sensei_config.json &

./main/main_app &

sleep 3

aconnect 16 128


